- routes/index.js
closes https://github.com/jonrohan/browserl.ist/issues/2
This uses the `browserslist.defaults` string for the default query instead of the hardcoded `> 5%`.
cc @ai
> Defaulting to the browserslist default string

- package.json
- routes/index.js
closes https://github.com/jonrohan/browserl.ist/issues/9
This pull updates browserslist and uses the new "defaults" query which will expand out the default browsers.
> Upgrading browserslist and using 'defaults'

- views/index.pug
Hi. Two small tweaks:
- Accessibility: empty alt on images instead of duplicating the browser name.
- Mobile layout: give more room to the header content on small viewports.
> HTML tweaks (accessibility and mobile style)

- routes/index.js
- views/index.pug
> Display regional stats for `in` queries

- routes/index.js
Thanks for building this site!
This partially fixes #55 to allow people to paste their browserslist config directly from a `package.json` file.
For instance, my `package.json` looks like this:
```
"browserslist": [
">0.19%",
"not dead",
"not ie <= 10",
"not op_mini all",
"ios_saf >= 9.0"
],
```
This PR allows me to copy/paste the following directly into the form and get the desired results:
```
">0.19%",     "not dead",     "not ie <= 10",     "not op_mini all",     "ios_saf >= 9.0"
```
Thanks for considering this PR, and please let me know if any questions/comments/suggestions!
> Strip quotation marks from query pasted from a package.json file.

- views/index.pug
This fixes issue #281 
The header at the top was renamed from `browserl.ist` to `browsersl.ist`
> Fixed spelling of browserl.ist => browsersl.ist

- server/lib/get-browsers.js
- server/test/browsers.test.js
Node.js doesn't have coverage statistics in `caniuse-lite`. We will output `null` instead of version usage coverage
It is better to consider this request after [#291](https://github.com/browserslist/browserl.ist/pull/291)
> Output Node versions without coverage in server

- server/api/browsers.js
- server/test/app.test.js
I removed smart region recognition from a query. This logic complicated the client requirements for MVP
#292
> Take region only from GET parameter

- server/api/browsers.js
- server/app.js
- server/lib/get-browsers.js
- server/test/app.test.js
The idea of `node:` prefix is to mark all Node.js imports since they are not ECMA standard.
> Add `node:` prefix to all node imports

- client/view/Form/form.js
- client/view/QueryLink/queryLink.js
- Replace `getUrlQuery()` to `submitFormWithUrlParams()`
- `submitForm(query, region)` split into: 
- `setValues({ query, region })`
- `submitForm()` 
- Fix bug: `initUrlControl` triggers twice (Removed this function)
- Big form submit handler moves to function `handleFormSubmit(e)`. Now all the functions are at the bottom of the file.
Closes #328
> Add current region to URL

- .github/workflows/test.yml
We called `pnpm test && pnpm test -r` on CI. When we added `pnpm test -r` to `pnpm test` we got calling `pnpm test -r` [twice](https://github.com/browserslist/browserl.ist/runs/7786201049?check_suite_focus=true)
> Do not call `pnpm test -r` twice on CI

- client/view/Form/form.js
> Fix submit bugs. Reset `region` query-parameter

- client/view/BrowserStats/BrowsersStat.css
The inscription is always at the bottom of the screen (or even lower if there is more content)
**Pros**
Versions are always in the same place and do not "jump"
**Cons**
If we take a screenshot, the version may be will not be included
**Merge after https://github.com/browserslist/browserl.ist/pull/356** (`v2` ← `v2-tools-versions`)
> Show `toolsVersions` caption at the bottom (sticky footer)

- client/view/Article/Article.css
Closes #348
I always hide scrollbar without "jumping". While I offer this **temporary** solution, it is already a little better than before.
---
But It seems that we will need to separate these two scroll areas. Or somehow synchronize them.
It's well described here:
https://github.com/browserslist/browsersl.ist/issues/310#issuecomment-1213038094
>  Remove double vertical scroll

- server/handlers/main.js
- server/handlers/static.js
- server/lib/get-file-data.js
- Replaced `fs` callbacks to promises
- Removed cache logic from the handler
- Add `favicon.ico` to memory cache
Closes #342
> Improve static file server

- server/handlers/main.js
- server/handlers/static.js
- server/lib/get-file-data.js
> Improve HTTP error handling

- .github/workflows/ci.yml
- .github/workflows/preview.yml
- client/package.json
- package.json
- server/package.json
> Refactor npm scripts

- client/index.html
- client/view/Article/Article.css
- client/view/Badge/Badge.css
- client/view/BrowserStats/BrowsersStat.css
We don’t have 100% Performance on Lighthouse because of big Cumulative Layout Shift.
It happens because many images do not have explicit size. The browser needs to load an image first and only then it will be able to calculate image size.
This PR set image sizes explicitly.
> Set image size to reduce CLS

- server/handlers/main.js
Fixes https://github.com/browserslist/browsersl.ist/issues/373
> Improve security headers

- client/view/base/colors.css
PostCSS not fallback css-variables from `@media`. Deleted `@media (preferences-color-scheme: light) {` to solve the problem
Closes #404 and (#401 duplicate)
> Fix CSS variables work in old browsers

- client/index.css
- client/view/base/base.css
Before, `base` had a special meaning. It imports other components (which it is not use) and do not follow CSS file name convention.
Now it is just a simple component.
> Fix CSS componants

- server/handlers/main.js
- server/handlers/static.js
According to [this threat](https://twitter.com/subzey/status/1559841999292882944).
1. Adding `; charset=utf-8` will avoid scaning for `<meta charset>`
2. With `must-revalidate` we disabled CDN caching
> Improve index.html headers

- client/index.html
- client/view/Form/Form.css
- client/view/Form/form.js
- client/view/Form/transformQuery.js
- server/handlers/api-browsers.js
- Multiline
- JSON
- JSON Fragment (without `{` and  `}` symbols)
Closes #388
Closes https://github.com/browserslist/browsersl.ist/issues/387
> Allow to write multiline/JSON configs in form

- server/lib/send-response.js
Fix bad `Content-Length` header calculating for responses with non-latin symbols
Closes #426
> Fix a broken API response to request with not-latin characters

- client/view/Form/form.js
Transform `rawQuery` to `query` not only for `fetch`, but also for `history.pushState`
> Make the query in the URL more readable

- client/index.html
- client/view/BrowserStats/BrowsersStat.css
- client/view/BrowserStats/browserStats.js
- client/view/Form/Form.css
- client/view/Form/form.js
- client/view/base/base.css
Show a placeholder with a hedgehog when the `<textarea>` is empty
**Other changes**
- Remove hint about required non-empty `<textarea>`
- Refactoring. Replace `*--hidden` BEM classes to `[hidden]` attribute
Closes #379
> Show a placeholder with a hedgehog when the `<textarea>` is empty

- server/handlers/api-browsers.js
Previously (v1 site) we cut quotes `'` on the server side.
It seems that now we don't need this logic if we want 1-1 matching queries. This is breaking-change.
> Disable quotes removing from `query` on server

- server/lib/get-browsers.js
- server/test/browsers.test.js
I did a refactoring `getBrowsers()` before fix audience coverage issues in https://github.com/browserslist/browsersl.ist/issues/423
I did it as the same way as in a similar PR https://github.com/browserslist/browsersl.ist/pull/371:
- `getBrowsers()` was simplified by moving from `return Promise(cb)` to `async function`
- `getBrowsers()` could always return non-standard error (outside of internal try-catch statement). Now we are ready for it.
Additional:
- Removed unused loop for check unique browsers versions `getBrowsers()`. [Browserslist ensures that all returnable values are unique](https://github.com/browserslist/browserslist/blob/eb83bb3865cab145e2c72ea73012d502b8a351b5/test/main.test.js#L43) 
- Added simple coverage test for `>1%` query
> Simplify `getBrowsers()` function

- client/view/BrowserStats/browserStats.js
- server/lib/get-browsers.js
This is an addition to PR https://github.com/browserslist/browsersl.ist/pull/438
I continue to simplify `getBrowsers()` before Issue https://github.com/browserslist/browsersl.ist/issues/423
**Changes**
- Refactor getting versions coverage
- Rename `browsersNames` → `browsersCoverageByQuery`
- Simplify temporary object
`{ node: { versions: { '18.5.0': 0 } } }` → `{ node: { '18.5.0': null } }`.
Before we created an object with `versions` field that was not used, only destructured
- Add output `—` for Node.js versions with `null` coverage
> Return `null` coverage for Node.js and output `—` symbol in stats

- client/index.css
- client/index.html
- client/index.js
- client/view/Form/Form.css
- client/view/Form/Form.js
- client/view/Skip/Skip.css
- client/view/Skip/Skip.js
> Improve a11y

- client/view/Form/Form.css
- client/view/Form/Form.js
- client/view/Form/loadBrowsersData.js
> Be ready for response wrong order

- client/view/QueryLink/QueryLink.js
Replaced innerText with textContent, that has access to hidden content
> Fix empty href in hidden `queryLinks`

- client/index.html
- client/view/DocSection/DocSection.css
- client/view/QueryLink/QueryLink.css
- client/view/base/base.css
Closes https://github.com/browserslist/browsersl.ist/issues/407
Closes https://github.com/browserslist/browsersl.ist/issues/395
> Add clicked state and improve extand button

- .github/workflows/update.yml
- README.md
- client/.size-limit.json
- client/index.html
- client/view/Form/Form.css
- client/view/Form/Form.js
- client/view/QueryLink/QueryLink.js
- pnpm-lock.yaml
- server/lib/get-browsers.js
- server/package.json
**Changes**
_UPD: it seems the server code is not updated in the preview_
**Questions**
- How to display multiple warnings? (**design**) Now I output with `. <br />`
- Should we do something for warning's a11y?
- Should we automatically update `browserslist-lint` every day (as `browserslist` and `caniuse-lite`)?
- Our first example with `defaults and supports es6-module` contains coverage errors :(
Closes #390
> Add browserslist-lint results

- client/index.html
- client/view/BrowserStats/BrowsersStat.css
I added links to npm packages from footer with `browserslist` and `caniuse-lite` versions.
1. It will be better to highlight versions a little
2. Users can use these links to check that it is really the latest versions
> Add links to npm package

- client/index.html
Should we set `rel="noopener noreferrer"` here and everywhere?
Or do wetotal trust the resources we are referring to and this is unnecessary?
> Add `target="blank"` to Badges

- client/view/Form/Form.js
- client/view/QueryLink/QueryLink.js
> Update region in links

- client/data/regions.js
> Sort countries by name

- client/view/Browsers/Browsers.js
**Test query**
_Before_
https://browsersl.ist/?q=since+0+or+unreleased+versions+or+Node+%3E+0
_After_
https://preview-474---browserslist-vw3nqlhdtq-ue.a.run.app/?q=since+0+or+unreleased+versions+or+Node+%3E+0
Closes #472
> Fix version sorting

- client/index.css
- client/index.html
- client/view/Alert/Alert.css
- client/view/Alert/Alert.js
- client/view/Base/colors.css
- client/view/Form/Form.css
- client/view/Form/Form.js
> Improve the hint with errors/warnings

- client/index.html
- client/view/Alert/Alert.js
- client/view/Base/colors.css
- client/view/Form/Form.js
There were a few problems of components separation in https://github.com/browserslist/browsersl.ist/pull/482
- `Form_messages` was styles in one component, but JS was added in another
- `Alert` knew too many things about `Form`. For instance, alert works with form’s `textarea` directly.
This PR split logic between component in a more gentle way. Yes, we have a problem with huge Form component.
I also changed error color, so it is more red-ish and closer to warning’s yellow in terms of chroma.
> Fix components composition

- client/view/Bar/Bar.js
Now, not-popular browsers has negative opacity. As the result, the visible part of the bar is smaller.
Before:
After:
> Fix bar opacity

- client/index.html
I believe the timestamp should be `Updated on DATE at TIME`. And therefore only `on` for date-only timestamps.
* https://forum.wordreference.com/threads/updated-on-or-at-april-4-2018-13-00-03.3484362/post-17687092
* https://english.stackexchange.com/a/182663
> Fix grammar in label of the last update timestamp

- client/index.html
Opera Mini seems to have 2 data saving modes:
- Extreme
- High
https://blogs.opera.com/news/2015/09/new-high-saving-data-opera-mini/
"High" seems to be compatible with Chrome.
[caniuse.com](caniuse.com) says "To test on iOS/Android this mode can be enabled using "Extreme data savings"".
In short, what we call `op_mini` is not the entire of Opera Mini but just one of its modes.
> Fix raw backticks

- client/view/QueryLink/QueryLink.js
@ialexryan [in this PR](https://github.com/browserslist/browsersl.ist/pull/495) reported a bug with incorrect value substitution in QueryLink's `href`:
`last 2 Safari major,            versions` instead of `list 2 Safari major versions` 
This error was caused by HTML formatting and automatic replacement of `\n` with `,`.
To fix it, I just removed all duplicate spaces and newline characters, because multiline queries and JSON queries are not supported in the QueryLink component right now (#433)
> Add HTML formatting errors handling to QueryLink

- client/scripts/build-regions.js
I checked the fix on macOS and Windows
> Fix the regions.json file path displayed in the console

- server/test/cache-static.test.js
- server/test/index.test.js
- server/test/set-production.js
Added a server's tests to improve DX — closes #374
P.S. I'm happy to see the work on the project goes on!
> Add a server test to check static file caching

- client/package.json
- client/scripts/build-regions.js
- client/test/build-regions.test.js
We have a `client/scripts/build-regions.js` that generates a list of countries from caniuse-lite on `postinstall` step.
I added a small tests so that we could notice that something is wrong in the caniuse database.
And, perhaps, the code will become a little clearer for contributors.
> Add tests for regions.json prebuild

- client/view/Form/Form.js
- client/view/Form/isEmptyConfig.js
Fixes the case when config consists of comment only.
https://github.com/browserslist/browsersl.ist/assets/35267898/16988ab2-210e-440d-987a-d390bc95cfce
> Add advanced check if config is empty

- client/view/QueryLink/QueryLink.js
Switching to `innerText` is fine for not dealing with spaces in JSON example. 
But it doesn't work with hidden elements.
> Fix query links

- client/view/Form/Form.js
- client/view/Form/loadBrowsers.js
Now we won't substitute region if it's not global (unfortunately we can't trust `alt-ww`)
> Not send `?region` param if region `alt-ww`

- README.md
- client/view/Form/Form.js
- client/view/Form/loadBrowsers.js
- server/handlers/api-browsers.js
- server/lib/get-browsers.js
- server/lib/get-coverage.js
- server/test/browsers.test.js
- server/test/index.test.js
I saw issues by @MonstraG (#512 & https://github.com/Fyrd/caniuse/issues/6811) about errors in browser usage statistics. 
Now we will use stats that is updated dayly/weekly, not once a month (how it is implemented in the `browserlist.coverage()`)
- Site show stats from **[region-usage-json/alt-ww.json](https://github.com/Fyrd/caniuse/blob/main/region-usage-json/alt-ww.json)**  — updated **monthly**
- `browserslist.coverage()` use global stats from **[data.json](https://github.com/Fyrd/caniuse/blob/main/data.json)** — updated **daily/weekly**
> Use up-to-date global coverage stats for browser versions

- client/view/Alert/Alert.js
- client/view/Form/Form.js
- client/view/QueryLink/QueryLink.js
Now we can send browserslist queries to Plausible. And we can better understand the purpose of these queries to analyze the needs of our users. 
<details>
<summary>Prev outdated PR description</summary>
In this PR I made a simple version, but we can send more events and see them in filters.
This will help us analyze the goal of sending a query by our users.
UPD
```js
trackEvent('Change region', { props: { region } }) // not remove
trackEvent('Open query', { props: { query } })
trackEvent('Fix query', { props: { query } }) // add "query" prop to "Fix query"
trackEvent('Enter query', { props: { query } })
trackEvent('Click on query', { props: { query } })
```
</details>
> Send browseslist queries to Plausible

- client/index.html
Do not merge till a version of browserslist that includes browserslist/browserslist#787 is used in this repo.
---
Update documentation for `fully supports` and `partially supports` as requested in browserslist/browserslist#787.
Update the feature support section to promote usage of `fully supports` and `partially supports`.
Note that `supports` is an alias of `partially supports` however suggest that user should  favor using `partially supports` as its intent is more explicit.
> Add `fully supports` and `partially supports`

- README.md
This PR removes the leading `>` operator from the example query string: `>defaults` is not [valid query syntax](https://github.com/browserslist/browserslist?tab=readme-ov-file#queries).
> README: use correct query string in HTTP API response example

- server/handlers/main.js
Sorry I did not see that there also was an `X-Frame-Options` header
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
> Remove `X-Frame-Options` protection from HEADER

- .github/workflows/ci.yml
- Dockerfile
- client/package.json
- package.json
- pnpm-lock.yaml
- scripts/check-versions.js
- scripts/run-image.sh
- server/index.js
- server/package.json
> New deploy
