browserslist/browsersl.ist

routes/index.js
views/index.pug

fixes https://github.com/jonrohan/browserl.ist/issues/1
Now when a query doesn't exist, the site will show the browserslist error.
cc @ai

Showing error when browser query doesn't exist

---

routes/index.js
views/index.pug
views/layout.pug

Hi, I've added to the report page the percentage of each browser and the total global coverage, just to know how many browser a specific query can target.

added global coverage for each browser

---

package.json

fix(package): update browserslist to version 2.9.0

---

package.json

Requires #133, I'll rebase after that is merged.

Update dependencies and move eslint in devDependencies.

---

.eslintrc.json
app.js
bin/www
package.json
routes/index.js

Just using the existent config.

Add a lint script, ES6-ify and lint code.

---

package.json

Let's leave this last @jonrohan.

Switch to Node.js 10

---

.github/workflows/test.yml
README.md

Add GitHub Actions CI.

---

.eslintrc.json
bin/www
package.json

Update eslint to v6.6.0 and eslint-plugin-github to v3.2.1

---

views/index.pug

> Node.js® is a JavaScript runtime built on Chrome's V8 JavaScript engine.
[nodejs.org](https://nodejs.org/en/)

Fix Node.js naming

---

LICENSE
README.md
public/stylesheets/style.css
views/layout.pug

This updates urls and wording around the move from jonrohan/browserl.ist to browserslist/browserl.ist

Updating the wording to reflect movement

---

public/stylesheets/style.css

Change selection coloring to red in `public/stylesheets/style.css`.

Added in selection color

---

client/data/regions.js
client/scripts/generate-regions-json.js
client/view/browsers/browsers.pug
client/view/browsers/index.css
client/view/browsers/index.js

**After #298**
- Add select with 2 optgroups `Continents` and `Countries`
- Add listening  `<select>`'s`change` event
- Separated rendering from getting data
- Update  listening `<input>`'s `input` event
**UPD:**
Now the .size-limit test is passed. Decrease script execute from `5.46kb` to `4.46 kB` with getting country name with `window.Intl`

Add `<select>` control for region. Fix .size-limit test

---

package.json
server/app.js

- Add `pnpm start` script for monorepo (from README.md)
- Show `server listening on ..`

Add `pnpm start` script for monorepo

---

.github/workflows/test.yml

Run `pnpm test` from the core and subprojects in parallel

Run all tests in parallel

---

pnpm-lock.yaml
server/package.json
server/test/app.test.js
server/test/browsers.test.js

- Uninstall `uvu`
- Rewrite tests to `node:test` 
- sync unit-tests
- async integration tests
Output looks not so cool as `uvu`, but works very fast. I tried to break a few tests - everything is fine
:)

Migrate tests from `uvu` to `node:test`

---

server/lib/get-browsers.js
server/test/browsers.test.js

Add browser coverage in the specified region

---

client/index.html
client/view/QueryLink/queryLink.js

Improve dx of query links

---

client/view/Form/form.js

handle network and 500 errors

---

client/view/Form/form.js

Errors display after click query-link

---

client/index.html
client/view/Article/Article.css
client/view/Badge/Badge.css
client/view/BrowserStats/BrowsersStat.css
client/view/DocSection/DocSection.css
client/view/Form/Form.css
client/view/QueryLink/queryLink.js

Fix some small bugs

---

client/index.html
client/view/BrowserStats/BrowsersStat.css

**Idea**
Always show caption at the bottom (as sticky footer)

Update alignment and typography for `toolsVersions` block

---

client/data/regions.js

Closes #352
FF with `ru-RU` locale test:

Use English name in countries list for consistency

---

client/view/Article/Article.css

Fix extra scrolls in the query area

---

client/index.html
client/view/QueryLink/queryLink.js

Scroll into view by clicking on `queryLink`

---

client/index.html
client/view/Article/Article.css
client/view/DocSection/DocSection.css
client/view/Form/Form.css

draft: Fix #361, #354 and some other bugs

---

client/view/BrowserStats/browserStats.js
server/lib/get-browsers.js

Merge after approve by designers
Closes #362

Sort versions by name not popularity

---

server/index.js

Fixes https://github.com/browserslist/browsersl.ist/issues/372

Add no-www redirect

---

server/index.js

Change default port

---

client/index.html
client/view/Article/Article.css
client/view/BrowserStats/BrowsersStat.css
client/view/BrowserStats/browserStats.js
client/view/DocSection/DocSection.css
server/index.js

Lots of improvements:
* better subtitle, headers, query syntax
* better query syntax and table formatting
* rounded percent values in the table
* @ai, I hope we can agree that "one digit after the dot" is a good enough precision for this table
* typos fixed here and there 
Looks great:

Improve text and its formatting

---

client/view/Form/Form.css

I removed this `<textarea />` behavior:
https://user-images.githubusercontent.com/22644149/184560369-ec18fb0b-4a75-4fb1-9bc9-1916d9b2a94f.mov

Allow to resize `<textarea>` only vertically

---

client/view/QueryLink/QueryLink.css
client/view/QueryLink/queryLink.js

Now we have a great SEO, but i have one question. 
Should this links lead to global region (like now), or when user change region, we should change all hrefs to the current region?
First option looks more reasonable.
Fixes #383.

make the query links real links - add the href attribute (#383)

---

client/view/Tweet/Tweet.css

Tweets focus outline is visible now

---

client/index.html

Fixes https://github.com/browserslist/browsersl.ist/issues/384
In US using `a - b` is more rare than in Russian. Also, I added more non-break spaces to balance line breaks.

Fix typography

---

README.md

Add HTTP API information to README.md

---

client/view/Form/transformQuery.js

Update multiline RegEx. Added TODO that we will need 1-1 parser
Related #433

Add `,` support to multiline config

---

client/index.html
client/view/Form/Form.css

Closes https://github.com/browserslist/browsersl.ist/issues/434

Allow to copy error message

---

client/view/BrowserStats/BrowserStats.js

Closes https://github.com/browserslist/browsersl.ist/issues/420

Add tooltip for small items in statistics bar

---

server/lib/get-browsers.js

Fix region coverage >100%

---

client/package.json
pnpm-lock.yaml
server/package.json

Temporary demo branch to monitor changes in caniuse statistics. https://github.com/Fyrd/caniuse/issues/6426
**https://preview-450---browserslist-vw3nqlhdtq-ue.a.run.app/**

Temporary demo with old caniuse-1.0.30001379

---

client/view/BrowserStats/BrowserStats.js

Display 2 decimal places if coverage is `<1%`

---

client/index.css
client/index.html
client/view/Article/Article.css
client/view/BrowserStats/BrowsersStat.css
client/view/Footer/Footer.css

Closes #392
(if everything is ok, then I will add to #459 with small fixes)

Add link to website source code

---

client/view/Badge/Badge.css
client/view/Footer/Footer.css
client/view/Versions/Versions.css

Fix badge text vertical alignment. Simplify footer

---

client/index.html
client/view/Link/Link.css

Closes https://github.com/browserslist/browsersl.ist/issues/465

Fix links active state

---

.github/workflows/ci.yml
client/package.json
client/view/Form/Form.js
client/view/QueryLink/QueryLink.js
package.json
server/handlers/api-browsers.js
server/handlers/main.js
server/handlers/static.js
server/index.js
server/lib/get-browsers.js
server/lib/get-file-data.js
server/lib/send-response.js
server/package.json
server/test/browsers.test.js
server/test/index.test.js

Closes https://github.com/browserslist/browsersl.ist/issues/428
Closes https://github.com/browserslist/browsersl.ist/issues/475
Also small changes:

Move to hash URL

---

client/view/Form/Form.js

Another way to fix https://github.com/browserslist/browsersl.ist/pull/478

Fix double fetch()

---

client/view/Form/loadBrowsers.js

There was a small syntax typo.

Fix link in error message

---

.prettierignore
client/index.html

Edits of the `index.html` automatically trigger prettier, which pollutes changes 🤷
UPD: Prettier makes HTML files ugly. Disabled Prettier on the project scope.

Format index page to avoid commits polluting with unexpected change

---

client/view/Form/transformConfig.js

Fixes #483 
https://github.com/browserslist/browsersl.ist/assets/35267898/c37a908e-940e-4063-8a31-7693249da676

Remove nasty input trimming

---

client/index.html

Update gitHub stars

---

client/index.html

Can read/review commit by commit. Tho it should be obvious, maintainers may cherrypick only the commits they want to have without involving any unnecessary turnaround.
[^1]
[^1]: Please consider [giving up MS GitHub](https://sfconservancy.org/GiveUpGitHub/) or offering a non-proprietary, non-US-corporate-controlled mirror for this free software project. I wish to delete this Microsoft account in the future, but I need more projects like this to support alternative methods to send patches & contribute.

Typo, typography, abbreviation
